### ISSUE TITLE
根据代码来看还不支持双向认证

### ISSUE THREAD

**Issue by glfov** [piligo/gmssl#1]
客户端握手过程不支持双向认证，代码里看还是用的源码部分，最多只能传递一份证书，sms4-cbc的私钥读取也有问题，请问是还没有做还是有什么限制不支持双向认证

**Comment by piligo** [comment]
> 客户端握手过程不支持双向认证，代码里看还是用的源码部分，最多只能传递一份证书，sms4-cbc的私钥读取也有问题，请问是还没有做还是有什么限制不支持双向认证

原来做的时候，没有双向认证的需求，后期由于没在项目组，项目组也基本上黄了，所以没有继续更新了

**Comment by piligo** [comment]
> 客户端握手过程不支持双向认证，代码里看还是用的源码部分，最多只能传递一份证书，sms4-cbc的私钥读取也有问题，请问是还没有做还是有什么限制不支持双向认证

目前看同济版本的  已经很丰富了，可以关注一下他们项目，也再持续迭代中，https://github.com/tjfoc/gmsm

**Comment by glfov** [comment]
> > 客户端握手过程不支持双向认证，代码里看还是用的源码部分，最多只能传递一份证书，sms4-cbc的私钥读取也有问题，请问是还没有做还是有什么限制不支持双向认证
> 
> 目前看同济版本的 已经很丰富了，可以关注一下他们项目，也再持续迭代中，https://github.com/tjfoc/gmsm

感谢回复，已自行解决
